dsw/ut1/matraka/main/main/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
]

dsw/ut1/matraka/main/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='post-list'),
    path('add/', views.add_post, name='add-post'),
    path('edit/', views.edit_post, name='edit-post'),
    path('<slug:post_slug>/', views.post_detail, name='post-detail'),
]

dsw/ut1/matraka/main/posts/models.py
from django.db import models


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=256)
    slug = models.SlugField(max_length=256)
    content = models.TextField()

    def __str__(self):
        return f'PK={self.pk}: {self.title}'

dsw/ut1/matraka/main/shared/models.py
from django.db import models

# Create your models here.

dsw/ut1/matraka/main/posts/forms.py
from django import forms

from .models import Post


class AddPostForm(forms.Form):
    class Meta:
        model = Post
        fields = ('title', 'content')


class EditPostForm(forms.Form):
    class Meta:
        model = Post
        fields = ('title', 'content')

dsw/ut1/matraka/main/posts/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.utils.text import slugify

from .forms import AddPostForm, EditPostForm
from .models import Post


def add_post(request):
    if request.method == 'POST':
        if (form := AddPostForm(request.POST)).is_valid():
            post = form.save(commit=False)
            post.slug = slugify(post.title)
            post.save()
            return redirect('posts:post-list')
    else:
        form = AddPostForm()
    return render(request, 'posts/post/add.html', dict(form=form))


def edit_post(request, post_slug: str):
    post = Post.objects.get(slug=post_slug)
    if request.method == 'POST':
        if (form := EditPostForm(request.POST, instance=post)).is_valid():
            post = form.save(commit=False)
            post.slug = slugify(post.title)
            post.save()
            return redirect('posts:post-list')
    else:
        form = EditPostForm(instance=post)
    return render(request, 'posts/edit_post.html', dict(post=post, form=form))


def post_list(request):
    posts = Post.objects.all()

    return render(request, 'posts/post/list.html', {'posts': posts})


def post_detail(request, post_slug: str):
    try:
        post = Post.objects.get(slug=post_slug)
    except Post.DoesNotExist:
        return HttpResponse(f'Post with slug "{post_slug}" does not exist!')
    return request('posts/post/detail.html', {'post': post})

dsw/ut1/matraka/main/shared/views.py
from django.shortcuts import render

# Create your views here.

dsw/ut1/matraka/main/posts/templates/posts/post/add.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Add post</title>
</head>
<body>

  
<h1>Post something.</h1>

  <form method="post" novalidate>
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="Enviar">
  </form>



</body>
</html>

dsw/ut1/matraka/main/posts/templates/posts/post/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>

  <h1>{{ post.title }}</h1>
  <p>{{ post.content }}</p>
  {% for post in posts %}
    <li>
    {% if forloop.first %}
        <em>{{ post }}</em>
        <strong>(Post más antiguo)</strong>
    {% else %}
        {{ post }}
    {% endif %}
    </li>
{% endfor %}


</body>
</html>

dsw/ut1/matraka/main/posts/templates/posts/post/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>

<h1>Editando post "{{ post.title }}"</h1>

<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Guardar">
</form>



</body>
</html>

dsw/ut1/matraka/main/posts/templates/posts/post/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UltimateBlog</title>
</head>
<body>
    {% extends "base.html" %}
    <ul>
   

{% block content %}
    <div class='cabezo'>{% include "header.html" with subtitle="Don't miss the cutting edge info!" %} </div>

    {% for post in posts %}
    {% comment "opcional" %}
    <p>hola</p>
    {% endcomment %}
        <h3>{{ post }}</h3>
        <p>Read more <a href="{% url 'posts:post-detail' post.id %}">here</a></p>
        <p>{% lorem 1 b random%}</p>
        <p>{% now 'd-m-Y' %}</p>
    {% endfor %}
        
        <ul>
    {% for post in posts %}
        <li style="background-color: {% cycle 'LightBlue' 'LightPink' %}">
            {{ post }}
        </li>
    {% endfor %}
                {% for post in posts %}
        <li>{{ post }}</li>
    {% empty %}
        <p>No posts so far!</p>
    {% endfor %}

    
</ul>
{% endblock %}



</ul>

</body>
</html>

dsw/ut1/matraka/main/shared/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% if title %}{{ title }} | {% endif %}Blog</title>

  </head>

  <body>
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    <div class="container">
        {% block content %}
        
        
        {% endblock %}
    </div>
  </body>
</html>

dsw/ut1/matraka/main/shared/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div class="header">
    <h1>The ultimate blog</h1>
    <h2>{{ subtitle }}</h1>
</div>

</body>
</html>